### ISSUE TITLE
cannot find the exact data file

### ISSUE THREAD

**Issue by chenxinfeng4** [lwillmore/QuantifyingDefeat#1]
[QuantifyingDefeat](https://github.com/lwillmore/QuantifyingDefeat)/[QuantifyBehavior](https://github.com/lwillmore/QuantifyingDefeat/tree/main/QuantifyBehavior)/behavior_clustering.ipynb

```
## Define inputs
Xs = pickle.load(open('features2.p','rb'))
sessions=list(Xs.keys())

N_feats = len(FEATURE_NAMES)

```
There is no data file as 'features2.p' downloaded from _sharefigure_.
![图片](https://user-images.githubusercontent.com/17546446/207858874-a173bfb4-cb37-4736-987d-d0f05b0fdde3.png)

![图片](https://user-images.githubusercontent.com/17546446/207858970-af84b601-38a9-4160-baef-75a85069df46.png)

**Comment by lwillmore** [comment]
hi this notebook is meant to be general use on your own data. features2.p is saved at the bottom the feature extraction notebook https://github.com/lwillmore/QuantifyingDefeat/blob/main/QuantifyBehavior/tracks2features.ipynb
